### ISSUE TITLE
Subfolder search fails: subFoldersEnumerator.hasMoreElements is not a function

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/removedupes#56]
When searching folders with subfolders, we fail iterating the subfolder elements:
```
Uncaught TypeError: subFoldersEnumerator.hasMoreElements is not a function
    traverseSearchFolderSubfolders chrome://removedupes/content/removedupes.js:255
    addSearchFolders chrome://removedupes/content/removedupes.js:215
    beginSearchForDuplicateMessages chrome://removedupes/content/removedupes.js:115
    searchAndRemoveDuplicateMessages chrome://removedupes/content/removedupes.js:79
    oncommand chrome://messenger/content/messenger.xhtml:1
```

**Comment by eyalroz** [comment]
Build with fix integrated: [removedupes_0.5.2b1_tbird.xpi.zip](https://github.com/eyalroz/removedupes/files/6880044/removedupes_0.5.2b1_tbird.xpi.zip)
